on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - uses: actions/download-artifact@v1
        with: 
          name: shp2mysql-win-64
      - name: Archive Windows
        run: |
          zip --junk-paths -r shp2mysql-win-64
      - uses: actions/download-artifact@v1
        with: 
          name: shp2mysql-source
      - name: Archive Source
        run: |
          tar -zcvf shp2mysql-source.tar.gz shp2mysql-source
      - name: Upload Release Asset
        id: upload-release-asset1 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./shp2mysql-win-64.zip
          asset_name: shp2mysql-win-64.zip
          asset_content_type: application/zip
      - name: Upload Release Asset
        id: upload-release-asset2 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./shp2mysql-source.tar.gz
          asset_name: shp2mysql-source.tar.gz
          asset_content_type: application/gzip
