name: Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install Dependences
      run: sudo apt install -y mingw-w64 win-iconv-mingw-w64-dev autopoint
    - name: autogen
      run: ./autogen.sh
    - name: configure 
      run: ./configure --host=x86_64-w64-mingw32 --enable-static --disable-shared LDFLAGS=-static
    - name: make
      run: make
    - name: Package
      run: |
        mkdir -p shp2mysql/
        cp src/shp2mysql.exe shp2mysql/
        cp /usr/x86_64-w64-mingw32/bin/iconv.dll shp2mysql/
        cp LICENSE shp2mysql/
        zip -r shp2mysql-win-64.zip shp2mysql/
    - uses: actions/upload-artifact@master
      with:
        name: shp2mysql-win-64.zip
        path: shp2mysql-win-64.zip
